// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBKFyV3b7f4LwXkt5XcMbHJllFY3leEs',
    appId: '1:380236578962:web:43e36811aebe3e379de64b',
    messagingSenderId: '380236578962',
    projectId: 'tangtee-f93e0',
    authDomain: 'tangtee-f93e0.firebaseapp.com',
    databaseURL: 'https://tangtee-f93e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangtee-f93e0.appspot.com',
    measurementId: 'G-L5QG11HVML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVsvYYMkyBqz9RY8ZwGFPj6uneIXxojI',
    appId: '1:380236578962:android:91654c44a882028b9de64b',
    messagingSenderId: '380236578962',
    projectId: 'tangtee-f93e0',
    databaseURL: 'https://tangtee-f93e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangtee-f93e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJpWejPRncFB9v3XOBO4o6p6V1THbAZM',
    appId: '1:380236578962:ios:481e3d57ed5751ce9de64b',
    messagingSenderId: '380236578962',
    projectId: 'tangtee-f93e0',
    databaseURL: 'https://tangtee-f93e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tangtee-f93e0.appspot.com',
    iosClientId: '380236578962-vkrlatp9mg2aj0vdkqosi616mj310t5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.tangteevs',
  );
}
